# Entries should follow the template below
# 
# name: Title for collection
# description: Brief description
# group: LDAP group(s) that should have access
- title: Editorial Photography
  description: Born digital photographs of people, events, exhibitions, and the building.
  groups: photostudio
- title: Object Photography
  description: Born digital photographs of objects in the CMA collection.  
  groups: photostudio
- title: Conservation Photography
  description: Photographs taken by conservation department staff such as before and after treatment photographs
  groups: conservation 
